/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MethodsFrames;

import source.Bag;
import source.PrivateAirport;

/**
 *
 * @author joses
 */
public class JFramePrivateAirport extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFramePrivateAirport
     */
    public JFramePrivateAirport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrivateAirport = new javax.swing.JLabel();
        btnAddPrivateAirport = new javax.swing.JButton();
        lblIdAirport = new javax.swing.JLabel();
        lblCityLocated = new javax.swing.JLabel();
        txtIdAiroport = new javax.swing.JTextField();
        lblAirportName = new javax.swing.JLabel();
        txtAirportName = new javax.swing.JTextField();
        lblCountryLocated = new javax.swing.JLabel();
        txtCityLocated = new javax.swing.JTextField();
        txtCountryLocated = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblPrivateAirport.setText("Aeropuerto Privado");

        btnAddPrivateAirport.setText("Guardar");
        btnAddPrivateAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrivateAirportActionPerformed(evt);
            }
        });

        lblIdAirport.setText("Id del Aeropuerto:");

        lblCityLocated.setText("Ciudad Ubicada:");

        lblAirportName.setText("Nombre del Aeropuerto:");

        lblCountryLocated.setText("Pais Ubicada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrivateAirport)
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCityLocated)
                    .addComponent(lblAirportName)
                    .addComponent(lblCountryLocated)
                    .addComponent(lblIdAirport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPrivateAirport)
                    .addComponent(txtAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCityLocated, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountryLocated, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAiroport, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPrivateAirport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdAirport)
                    .addComponent(txtIdAiroport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirportName)
                    .addComponent(txtAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityLocated)
                    .addComponent(txtCityLocated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountryLocated)
                    .addComponent(txtCountryLocated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddPrivateAirport)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPrivateAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrivateAirportActionPerformed
        var idAirport = this.txtIdAiroport.getText();
        var nameAirport = this.txtAirportName.getText();
        var cityLocated = this.txtCityLocated.getText();
        var countryLocated = this.txtCountryLocated.getText();
        PrivateAirport privateAirport = new PrivateAirport(idAirport, nameAirport, cityLocated, countryLocated);
        
        var bag = Bag.getInstance();
        bag.addAirport(privateAirport);
        
        setDefaultCloseOperation(JFramePrivateAirport.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnAddPrivateAirportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrivateAirport;
    private javax.swing.JLabel lblAirportName;
    private javax.swing.JLabel lblCityLocated;
    private javax.swing.JLabel lblCountryLocated;
    private javax.swing.JLabel lblIdAirport;
    private javax.swing.JLabel lblPrivateAirport;
    private javax.swing.JTextField txtAirportName;
    private javax.swing.JTextField txtCityLocated;
    private javax.swing.JTextField txtCountryLocated;
    private javax.swing.JTextField txtIdAiroport;
    // End of variables declaration//GEN-END:variables
}
