package MethodsFrames;

import javax.swing.DefaultComboBoxModel;
import source.Bag;
import source.Passenger;


public class JFramePasajero extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFramePasajero
     */
    public JFramePasajero() {
        initComponents();
        var bag = Bag.getInstance();
        
        var flights = bag.getFlights().values();
        var items = flights.stream().map(flight -> flight.toStringBag()).toArray();
        
        cmbFlights.setModel(new DefaultComboBoxModel(items));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitelPassenger = new javax.swing.JLabel();
        nameP = new javax.swing.JLabel();
        numberP = new javax.swing.JLabel();
        nationalityP = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPassportNumber = new javax.swing.JTextField();
        btnAddPassenger = new javax.swing.JButton();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblVuelos = new javax.swing.JLabel();
        cmbFlights = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblTitelPassenger.setText("Registro de pasajero");

        nameP.setText("Nombre:");

        numberP.setText("Numero de pasaporte:");

        nationalityP.setText("Nacionalidad:");

        txtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalityActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtPassportNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassportNumberActionPerformed(evt);
            }
        });

        btnAddPassenger.setText("Guardar");
        btnAddPassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPassengerMouseClicked(evt);
            }
        });
        btnAddPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPassengerActionPerformed(evt);
            }
        });

        lblApellido.setText("Apellido:");

        lblVuelos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVuelos.setText("Vuelos disponibles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberP)
                            .addComponent(nationalityP)
                            .addComponent(nameP)
                            .addComponent(lblApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddPassenger)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNationality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassportNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(cmbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTitelPassenger)
                    .addComponent(lblVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblApellido, nameP, nationalityP, numberP});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtApellido, txtName, txtNationality, txtPassportNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblVuelos)
                .addGap(18, 18, 18)
                .addComponent(cmbFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(lblTitelPassenger)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameP)
                        .addGap(39, 39, 39)
                        .addComponent(lblApellido)
                        .addGap(39, 39, 39)
                        .addComponent(numberP)
                        .addGap(41, 41, 41)
                        .addComponent(nationalityP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtPassportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(btnAddPassenger)
                .addGap(41, 41, 41))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtApellido, txtName, txtNationality, txtPassportNumber});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed

    }//GEN-LAST:event_txtNationalityActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPassportNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassportNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassportNumberActionPerformed

    private void btnAddPassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPassengerMouseClicked
    }//GEN-LAST:event_btnAddPassengerMouseClicked

    private void btnAddPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPassengerActionPerformed
        var firstName = this.txtName.getText();
        var lastName = this.txtApellido.getText();
        var passportNumber = this.txtPassportNumber.getText();
        var nationality = this.txtNationality.getText();
        
        var passenger = new Passenger(firstName, lastName, passportNumber, nationality);
        
        var selectedFlight = (String) this.cmbFlights.getSelectedItem();
        
        var flightComponents = selectedFlight.split(":");
        var flightId = flightComponents[0];
        
        var bag = Bag.getInstance();
        var flight = bag.getFlights().get(flightId);
        
        flight.addPassenger(passenger);
        
        bag.addFlight(flight);
        
        setDefaultCloseOperation(JFramePasajero.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnAddPassengerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPassenger;
    public static javax.swing.JComboBox<String> cmbFlights;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblTitelPassenger;
    private javax.swing.JLabel lblVuelos;
    private javax.swing.JLabel nameP;
    private javax.swing.JLabel nationalityP;
    private javax.swing.JLabel numberP;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JTextField txtNationality;
    public static javax.swing.JTextField txtPassportNumber;
    // End of variables declaration//GEN-END:variables
}
