package MethodsFrames;

import AddingFrames.JFrameAddCorporate;
import AddingFrames.JFrameAddCompany;
import AddingFrames.JFrameAddFlight;
import AddingFrames.JFrameAddAirport;

public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Aeropuerto");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuAirportManager = new javax.swing.JMenu();
        mniAddAirport = new javax.swing.JMenuItem();
        mniConsultAirport = new javax.swing.JMenuItem();
        mniListFlightsByCompanyName = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        mniAddFlight = new javax.swing.JMenuItem();
        mnuCompany = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mniAddCompany = new javax.swing.JMenuItem();
        mnuPassenger = new javax.swing.JMenu();
        mniAddPassenger = new javax.swing.JMenuItem();
        mnuCorporate = new javax.swing.JMenu();
        mniAddCorporate = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuAirportManager.setText("Manejo de Aeropuertos");

        mniAddAirport.setText("Añadir aeropuerto");
        mniAddAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddAirportActionPerformed(evt);
            }
        });
        mnuAirportManager.add(mniAddAirport);

        mniConsultAirport.setText("Consultar aeropuerto");
        mniConsultAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultAirportActionPerformed(evt);
            }
        });
        mnuAirportManager.add(mniConsultAirport);

        mniListFlightsByCompanyName.setText("Listar vuelos por compania");
        mniListFlightsByCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListFlightsByCompanyNameActionPerformed(evt);
            }
        });
        mnuAirportManager.add(mniListFlightsByCompanyName);

        jMenuItem7.setText("Mostrar companias por aeropuerto");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuAirportManager.add(jMenuItem7);

        jMenuItem8.setText("Mostrar todas las companias");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuAirportManager.add(jMenuItem8);

        menuBar.add(mnuAirportManager);

        jMenu2.setText("Vuelos");

        jMenuItem9.setText("Mostrar vuelos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        mniAddFlight.setText("Añadir vuelo");
        mniAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddFlightActionPerformed(evt);
            }
        });
        jMenu2.add(mniAddFlight);

        menuBar.add(jMenu2);

        mnuCompany.setText("Compañias");

        jMenuItem10.setText("Mostrar vuelos por id");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mnuCompany.add(jMenuItem10);

        jMenuItem11.setText("Mostrar destinos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mnuCompany.add(jMenuItem11);

        mniAddCompany.setText("Añadir compañias");
        mniAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddCompanyActionPerformed(evt);
            }
        });
        mnuCompany.add(mniAddCompany);

        menuBar.add(mnuCompany);

        mnuPassenger.setText("Pasajero");

        mniAddPassenger.setText("Añadir Pasajero");
        mniAddPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddPassengerActionPerformed(evt);
            }
        });
        mnuPassenger.add(mniAddPassenger);

        menuBar.add(mnuPassenger);

        mnuCorporate.setText("Empresas");

        mniAddCorporate.setText("Añadir empresa");
        mniAddCorporate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddCorporateActionPerformed(evt);
            }
        });
        mnuCorporate.add(mniAddCorporate);

        menuBar.add(mnuCorporate);

        jMenu4.setText("Opciones");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        menuBar.add(jMenu4);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAddAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddAirportActionPerformed
        JFrameAddAirport airport = new JFrameAddAirport();
        desktopPane.add(airport);
        airport.toFront();
        airport.show();
    }//GEN-LAST:event_mniAddAirportActionPerformed

    private void mniConsultAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultAirportActionPerformed
        JFrameConsultAirport consultAirports = new JFrameConsultAirport();
        desktopPane.add(consultAirports);
        consultAirports.toFront();
        consultAirports.show();
    }//GEN-LAST:event_mniConsultAirportActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        JFrameMostrarDestinos mostrarDestinos = new JFrameMostrarDestinos();
        mostrarDestinos.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
         JFrameVuelos vuelos = new JFrameVuelos();
         vuelos.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JFrameCompanyMostrarVuelosId mostrarVuelos = new JFrameCompanyMostrarVuelosId();
        mostrarVuelos.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void mniListFlightsByCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListFlightsByCompanyNameActionPerformed
        JFrameListCompanies listComopanies = new JFrameListCompanies();
        desktopPane.add(listComopanies);
        listComopanies.toFront();
        listComopanies.show();
    }//GEN-LAST:event_mniListFlightsByCompanyNameActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JFrameMostrarCompaniasAero mostrarCompa = new JFrameMostrarCompaniasAero();
        mostrarCompa.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JFrameMostrarCompanias mostrarComAero = new JFrameMostrarCompanias();
        mostrarComAero.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void mniAddPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddPassengerActionPerformed
        JFramePasajero pasajero = new JFramePasajero();
        desktopPane.add(pasajero);
        pasajero.toFront();
        pasajero.show();
    }//GEN-LAST:event_mniAddPassengerActionPerformed

    private void mniAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddFlightActionPerformed
        JFrameAddFlight addFlight = new JFrameAddFlight();
        desktopPane.add(addFlight);
        addFlight.toFront();
        addFlight.show();
    }//GEN-LAST:event_mniAddFlightActionPerformed

    private void mniAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddCompanyActionPerformed
        JFrameAddCompany addCompany = new JFrameAddCompany();
        desktopPane.add(addCompany);
        addCompany.toFront();
        addCompany.show();
    }//GEN-LAST:event_mniAddCompanyActionPerformed

    private void mniAddCorporateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddCorporateActionPerformed
        JFrameAddCorporate addCorporate = new JFrameAddCorporate();
        desktopPane.add(addCorporate);
        addCorporate.toFront();
        addCorporate.show();
    }//GEN-LAST:event_mniAddCorporateActionPerformed

    public static void main(String args[]) {
          java.awt.EventQueue.invokeLater(() -> {
                new MDIPrincipal().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mniAddAirport;
    private javax.swing.JMenuItem mniAddCompany;
    private javax.swing.JMenuItem mniAddCorporate;
    private javax.swing.JMenuItem mniAddFlight;
    private javax.swing.JMenuItem mniAddPassenger;
    private javax.swing.JMenuItem mniConsultAirport;
    private javax.swing.JMenuItem mniListFlightsByCompanyName;
    private javax.swing.JMenu mnuAirportManager;
    private javax.swing.JMenu mnuCompany;
    private javax.swing.JMenu mnuCorporate;
    private javax.swing.JMenu mnuPassenger;
    // End of variables declaration//GEN-END:variables

}
