package AddingFrames;
import static MethodsFrames.JFramePasajero.cmbFlights;
import javax.swing.DefaultComboBoxModel;
import source.Bag;
import source.Flight;

public class JFrameAddFlight extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFrameAddFlight
     */
    public JFrameAddFlight() {
        initComponents();
        var bag = Bag.getInstance();
        var companies = bag.getCompany().values();
        
        var items = companies.stream().map(company -> company.toStringBag()).toArray();
        cmbCompanies.setModel(new DefaultComboBoxModel(items));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitleFlights = new javax.swing.JLabel();
        lblIdFlight = new javax.swing.JLabel();
        lblFlightOrigin = new javax.swing.JLabel();
        lblTravelPrice = new javax.swing.JLabel();
        lblReservedSeats = new javax.swing.JLabel();
        lblMaximumPassengers = new javax.swing.JLabel();
        lblFlightDetination = new javax.swing.JLabel();
        btnAddFlight = new javax.swing.JButton();
        txtTravelPrice = new javax.swing.JTextField();
        txtReservedSeats = new javax.swing.JTextField();
        txtMaximumPassengers = new javax.swing.JTextField();
        txtFlightOrigin = new javax.swing.JTextField();
        txtFlightDestination = new javax.swing.JTextField();
        txtIdFlight = new javax.swing.JTextField();
        lblCompanies = new javax.swing.JLabel();
        cmbCompanies = new javax.swing.JComboBox<>();
        lblCompanyOption = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblTitleFlights.setText("Añadir un nuevo vuelo");

        lblIdFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdFlight.setText("Id del vuelo:");
        lblIdFlight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblFlightOrigin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlightOrigin.setText("Vuelo de origen:");
        lblFlightOrigin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblTravelPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTravelPrice.setText("Costo del vuelo:");
        lblTravelPrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblReservedSeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReservedSeats.setText("Asientos reservados:");
        lblReservedSeats.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblMaximumPassengers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaximumPassengers.setText("Maximo de pasajeros:");
        lblMaximumPassengers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblFlightDetination.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlightDetination.setText("Destino del vuelo:");
        lblFlightDetination.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblFlightDetination.setMaximumSize(new java.awt.Dimension(64, 22));
        lblFlightDetination.setMinimumSize(new java.awt.Dimension(64, 22));
        lblFlightDetination.setPreferredSize(new java.awt.Dimension(64, 22));

        btnAddFlight.setText("Guardar");
        btnAddFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFlightMouseClicked(evt);
            }
        });
        btnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightActionPerformed(evt);
            }
        });

        txtIdFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFlightActionPerformed(evt);
            }
        });

        lblCompanies.setText("Compañias");

        lblCompanyOption.setText("Escoja la compania a la que desea añadir el vuelo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFlightDetination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReservedSeats)
                                    .addComponent(lblMaximumPassengers)
                                    .addComponent(lblTravelPrice)
                                    .addComponent(lblFlightOrigin))
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTravelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReservedSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaximumPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFlightOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFlightDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(txtIdFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCompanyOption)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(lblTitleFlights))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(lblCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmbCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblFlightDetination, lblFlightOrigin, lblIdFlight, lblMaximumPassengers, lblReservedSeats, lblTravelPrice});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFlightDestination, txtFlightOrigin, txtIdFlight, txtMaximumPassengers, txtReservedSeats, txtTravelPrice});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCompanies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompanyOption)
                .addGap(11, 11, 11)
                .addComponent(cmbCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblTitleFlights)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdFlight))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlightOrigin))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFlightDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlightDetination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaximumPassengers)
                    .addComponent(txtMaximumPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReservedSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReservedSeats))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTravelPrice)
                    .addComponent(txtTravelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFlightDestination, txtFlightOrigin, txtIdFlight, txtMaximumPassengers, txtReservedSeats, txtTravelPrice});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFlightDetination, lblFlightOrigin, lblIdFlight, lblMaximumPassengers, lblReservedSeats, lblTravelPrice});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFlightActionPerformed

    private void btnAddFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFlightMouseClicked
    }//GEN-LAST:event_btnAddFlightMouseClicked

    private void btnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightActionPerformed
        var idFlight = this.txtIdFlight.getText();
        var flightOrigin = this.txtFlightOrigin.getText();
        var flightDestination = this.txtFlightDestination.getText();
        int travelPrice = Integer.parseInt(this.txtTravelPrice.getText());
        var maximumPassengers = Integer.parseInt(this.txtMaximumPassengers.getText());
        var reservedSeats = Integer.parseInt(this.txtReservedSeats.getText());      
        Flight flight = new Flight(idFlight, flightOrigin, flightDestination, travelPrice, maximumPassengers, reservedSeats);
        
        var bag = Bag.getInstance();
        var selectedCompany = (String) cmbCompanies.getSelectedItem();
        
        var companyComponents = selectedCompany.split(":");
        var companyId = companyComponents[0];
        var company = bag.getCompany().get(companyId);
        company.addFlight(flight);
        
        bag.addFlight(flight);
        
        setDefaultCloseOperation(JFrameAddFlight.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnAddFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlight;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCompanies;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblCompanies;
    private javax.swing.JLabel lblCompanyOption;
    private javax.swing.JLabel lblFlightDetination;
    private javax.swing.JLabel lblFlightOrigin;
    private javax.swing.JLabel lblIdFlight;
    private javax.swing.JLabel lblMaximumPassengers;
    private javax.swing.JLabel lblReservedSeats;
    private javax.swing.JLabel lblTitleFlights;
    private javax.swing.JLabel lblTravelPrice;
    private javax.swing.JTextField txtFlightDestination;
    private javax.swing.JTextField txtFlightOrigin;
    private javax.swing.JTextField txtIdFlight;
    private javax.swing.JTextField txtMaximumPassengers;
    private javax.swing.JTextField txtReservedSeats;
    private javax.swing.JTextField txtTravelPrice;
    // End of variables declaration//GEN-END:variables
}
