/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AddingFrames;

import MethodsFrames.JFramePrivateAirport;
import MethodsFrames.JFramePublicAriport;
import static MethodsFrames.MDIPrincipal.desktopPane;

/**
 *
 * @author joses
 */
public class JFrameAddAirport extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFrameAddAirport
     */
    public JFrameAddAirport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAirports = new javax.swing.JLabel();
        lblAirportType = new javax.swing.JLabel();
        cmbAirportType = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblAirports.setText("Aeropuertos");

        lblAirportType.setText("Escoga el tipo de Aeropuerto que desea añadir:");

        cmbAirportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aeropuerto Privado", "Aeropuerto Publico" }));
        cmbAirportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAirportTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbAirportType, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(lblAirports))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(lblAirportType))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAirports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAirportType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbAirportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAirportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAirportTypeActionPerformed
        String desition = (String) cmbAirportType.getSelectedItem();
        switch(desition) {
            case "Aeropuerto Publico" :
                JFramePublicAriport publicAirport = new JFramePublicAriport();
                desktopPane.add(publicAirport);
                publicAirport.toFront();
                publicAirport.show();
                break;
            case "Aeropuerto Privado" :
                JFramePrivateAirport privateAirport = new JFramePrivateAirport();
                desktopPane.add(privateAirport);
                privateAirport.toFront();
                privateAirport.show();
                break;
        }
    }//GEN-LAST:event_cmbAirportTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAirportType;
    private javax.swing.JLabel lblAirportType;
    private javax.swing.JLabel lblAirports;
    // End of variables declaration//GEN-END:variables
}
