/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AddingFrames;

import javax.swing.DefaultComboBoxModel;
import source.Bag;
import source.Company;

/**
 *
 * @author joses
 */
public class JFrameAddCompany extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFrameAddCompany
     */
    public JFrameAddCompany() {
        initComponents();
        
        var bag = Bag.getInstance();
        var airports = bag.getAirport().values();
        
        var items = airports.stream().map(airport -> airport.toStringBag()).toArray();
        
       cmbAirports.setModel(new DefaultComboBoxModel(items));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompany = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        btnAddCompany = new javax.swing.JButton();
        lblIdCompany = new javax.swing.JLabel();
        txtIdCompany = new javax.swing.JTextField();
        lblbAirport = new javax.swing.JLabel();
        lblChooseAiroport = new javax.swing.JLabel();
        cmbAirports = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblCompany.setText("Añadir compania");

        jLabel1.setText("Nombre de la compania:");

        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });

        btnAddCompany.setText("Guardar");
        btnAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompanyActionPerformed(evt);
            }
        });

        lblIdCompany.setText("Id de la compania");

        txtIdCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCompanyActionPerformed(evt);
            }
        });

        lblbAirport.setText("Aeropuertos");

        lblChooseAiroport.setText("Escoja el aeropuerto que desea añadir el vuelo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblIdCompany))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCompany)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbAirport)
                            .addComponent(lblCompany)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChooseAiroport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(cmbAirports, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, lblIdCompany});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCompany, lblbAirport});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblbAirport)
                .addGap(11, 11, 11)
                .addComponent(lblChooseAiroport)
                .addGap(22, 22, 22)
                .addComponent(cmbAirports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblCompany)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdCompany)
                    .addComponent(txtIdCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnAddCompany)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void btnAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompanyActionPerformed
        var idCompany = this.txtIdCompany.getText();
        var companyName = this.txtCompanyName.getText();
        Company company = new Company(idCompany, companyName);       

        var bag = Bag.getInstance();
        var selectedAirport = (String) cmbAirports.getSelectedItem();
        var airportComponents = selectedAirport.split(":");
        var airportId = airportComponents[0];
        var airport = bag.getAirport().get(airportId);
        airport.addCompany(company);
        bag.addCompany(company);
        
        setDefaultCloseOperation(JFrameAddCompany.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_btnAddCompanyActionPerformed

    private void txtIdCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCompanyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCompany;
    private javax.swing.JComboBox<String> cmbAirports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblChooseAiroport;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblIdCompany;
    private javax.swing.JLabel lblbAirport;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtIdCompany;
    // End of variables declaration//GEN-END:variables
}
